export const notifications = [
    {
        id: 1,
        color: 1,
        title: 'Asset Notification',
        priority: 3,
        datetime: '07/23/23 1:12PM',
        name: 'Trailer 4482',
        infoText: 'Temp Violation',
        infoValue: '101F',
    },
    {
        id: 2,
        color: 2,
        title: 'Asset Notification',
        priority: 1,
        datetime: '07/23/23 1:12PM',
        name: 'Trailer 4482',
        infoText: 'Temp Violation',
        infoValue: '101F',
    },
    {
        id: 3,
        color: 3,
        title: 'Asset Notification',
        priority: 3,
        datetime: '07/23/23 1:12PM',
        name: 'Trailer 4482',
        infoText: 'Temp Violation',
        infoValue: '101F',
    },
    {
        id: 4,
        color: 4,
        title: 'Asset Notification',
        priority: 3,
        datetime: '07/23/23 1:12PM',
        name: 'Trailer 4482',
        infoText: 'Temp Violation',
        infoValue: '101F',
    },
    {
        id: 5,
        color: 3,
        title: 'Asset Notification',
        priority: 2,
        datetime: '07/23/23 1:12PM',
        name: 'Trailer 4482',
        infoText: 'Temp Violation',
        infoValue: '101F',
    },
    {
        id: 6,
        color: 2,
        title: 'Asset Notification',
        priority: 5,
        datetime: '07/23/23 1:12PM',
        name: 'Trailer 4482',
        infoText: 'Temp Violation',
        infoValue: '101F',
    },
];
